package com.dn.sports.ormbean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bodyRecordDaoConfig;

    private final BodyRecordDao bodyRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bodyRecordDaoConfig = daoConfigMap.get(BodyRecordDao.class).clone();
        bodyRecordDaoConfig.initIdentityScope(type);

        bodyRecordDao = new BodyRecordDao(bodyRecordDaoConfig, this);

        registerDao(BodyRecord.class, bodyRecordDao);
    }
    
    public void clear() {
        bodyRecordDaoConfig.clearIdentityScope();
    }

    public BodyRecordDao getBodyRecordDao() {
        return bodyRecordDao;
    }

}
