package com.dn.sports.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dn.sports.ormbean.BodyRecord;
import com.dn.sports.ormbean.StepCountRecord;

import com.dn.sports.bean.BodyRecordDao;
import com.dn.sports.bean.StepCountRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bodyRecordDaoConfig;
    private final DaoConfig stepCountRecordDaoConfig;

    private final BodyRecordDao bodyRecordDao;
    private final StepCountRecordDao stepCountRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bodyRecordDaoConfig = daoConfigMap.get(BodyRecordDao.class).clone();
        bodyRecordDaoConfig.initIdentityScope(type);

        stepCountRecordDaoConfig = daoConfigMap.get(StepCountRecordDao.class).clone();
        stepCountRecordDaoConfig.initIdentityScope(type);

        bodyRecordDao = new BodyRecordDao(bodyRecordDaoConfig, this);
        stepCountRecordDao = new StepCountRecordDao(stepCountRecordDaoConfig, this);

        registerDao(BodyRecord.class, bodyRecordDao);
        registerDao(StepCountRecord.class, stepCountRecordDao);
    }
    
    public void clear() {
        bodyRecordDaoConfig.clearIdentityScope();
        stepCountRecordDaoConfig.clearIdentityScope();
    }

    public BodyRecordDao getBodyRecordDao() {
        return bodyRecordDao;
    }

    public StepCountRecordDao getStepCountRecordDao() {
        return stepCountRecordDao;
    }

}
