package com.dn.sports.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dn.sports.ormbean.StepCountRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "step_record_new".
*/
public class StepCountRecordDao extends AbstractDao<StepCountRecord, Long> {

    public static final String TABLENAME = "step_record_new";

    /**
     * Properties of entity StepCountRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StartTime = new Property(1, long.class, "startTime", false, "START_TIME");
        public final static Property UseTime = new Property(2, long.class, "useTime", false, "USE_TIME");
        public final static Property Steps = new Property(3, int.class, "steps", false, "STEPS");
        public final static Property CurrentTime = new Property(4, long.class, "currentTime", false, "CURRENT_TIME");
        public final static Property Date = new Property(5, String.class, "date", false, "DATE");
        public final static Property Type = new Property(6, int.class, "type", false, "TYPE");
        public final static Property SubType = new Property(7, int.class, "subType", false, "SUB_TYPE");
    }


    public StepCountRecordDao(DaoConfig config) {
        super(config);
    }
    
    public StepCountRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"step_record_new\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"START_TIME\" INTEGER NOT NULL ," + // 1: startTime
                "\"USE_TIME\" INTEGER NOT NULL ," + // 2: useTime
                "\"STEPS\" INTEGER NOT NULL ," + // 3: steps
                "\"CURRENT_TIME\" INTEGER NOT NULL ," + // 4: currentTime
                "\"DATE\" TEXT," + // 5: date
                "\"TYPE\" INTEGER NOT NULL ," + // 6: type
                "\"SUB_TYPE\" INTEGER NOT NULL );"); // 7: subType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"step_record_new\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StepCountRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStartTime());
        stmt.bindLong(3, entity.getUseTime());
        stmt.bindLong(4, entity.getSteps());
        stmt.bindLong(5, entity.getCurrentTime());
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(6, date);
        }
        stmt.bindLong(7, entity.getType());
        stmt.bindLong(8, entity.getSubType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StepCountRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStartTime());
        stmt.bindLong(3, entity.getUseTime());
        stmt.bindLong(4, entity.getSteps());
        stmt.bindLong(5, entity.getCurrentTime());
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(6, date);
        }
        stmt.bindLong(7, entity.getType());
        stmt.bindLong(8, entity.getSubType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StepCountRecord readEntity(Cursor cursor, int offset) {
        StepCountRecord entity = new StepCountRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // startTime
            cursor.getLong(offset + 2), // useTime
            cursor.getInt(offset + 3), // steps
            cursor.getLong(offset + 4), // currentTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // date
            cursor.getInt(offset + 6), // type
            cursor.getInt(offset + 7) // subType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StepCountRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStartTime(cursor.getLong(offset + 1));
        entity.setUseTime(cursor.getLong(offset + 2));
        entity.setSteps(cursor.getInt(offset + 3));
        entity.setCurrentTime(cursor.getLong(offset + 4));
        entity.setDate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.getInt(offset + 6));
        entity.setSubType(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StepCountRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StepCountRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StepCountRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
